name: Monthly Trunk Upgrade
on:
  schedule:
    # On the first day of every month @ 8am
    - cron: 0 8 1 * *
    # Allows us to manually run the workflow from Actions UI
  workflow_dispatch: {}
permissions: read-all
jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@4d5ecc89b2691705fd08c747c78652d2fc806a94 # v1.1.19
        with:
          base: main
          reviewers: "@masterpointio/masterpoint-internal"
          prefix: "chore: "
